function onSuccess () {
    console.log("Hurray âœ”");
}

function onError () {
    console.log("ðŸ’©")
}

const promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    //resolve();
    reject();
  }, 3000);
})

promise.then(onSuccess);
promise.catch(onError);

// console.log(promise)

let p = new Promise((resolve, reject) => {
    let a = 1 + 4
    if (a == 6) {
        resolve('âœ”')
    } else {
        reject('ðŸ’©ðŸ’©ðŸ’©')
    }
})

p.then(message => {
    console.log('This is the then ' + message)
}).catch(message => {
    console.log('This is the catch ' + message)
})
